server:
  port: 8016
spring:
  application:
    name: ribbon-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#ribbon:
  # 属性配置自定义规则
  #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
  # Eager加载 默认情况下Ribbon是懒加载的——首次请求Ribbon相关类才会初始化，这会导致首次请求过慢的问题，你可以配置饥饿加载，让Ribbon在应用启动时就初始化
  #eager-load:
    #enabled: true
    #clients: provider-user #多个用,分隔

# 属性配置自定义规则
#provider-user:
  #ribbon:
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule