server:
  port: 8011
spring:
  application:
    name: provider-user   # 指定注册到eureka server上的服务名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/    # 指定eureka server通信地址，注意/eureka/小尾巴不能少
  instance:
    prefer-ip-address: true   # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server